# Database.DbConnections.UnitTest

DatabaseName    : 'unittest'        # Database name
Host            : 'socsrv'          # Host name or IP address
DriverName      : 'postgres'        # Driver name
UserName        : 'postgres'        # Login user
Password        : '???'             # Login password
Port            : 5432              # Port number, 5432 for PostgresV13, 5433 for V14
ServerSharePath    : '/var/samba/pgshare'   # Linux
MountSharePath     : '/media/gauss_pgshare' # Linux
WinMountSharePath  : 'S:/'                  # Windows (run: net use S: \\gauss\pgshare)

