SIMPLE : [true]
BITPIX : [-32]
NAXIS : [NaN]
NAXIS1 : [NaN]
NAXIS2 : [NaN]
ORIGIN : []
CREATOR: []
TELESCOP: []
INSTRUME: []
OBSERVER: []
IMTYPE: []
DATE-OBS: []
UTC-OBS: []
REFERENC: []
FILTER: []
EXPTIME: []
GAIN: []
READNOI: []
OBSJD: []
OBSMJD: []
MIDJD: []
OBSLST: []
OBSLON: []
OBSLAT: []
OBSNAME: []
PIXSCALE: []
RA: []
DEC: []
HA: []
M_RA: []
M_DEC: []
M_HA: []
M_EQUI: []
T_RA: []
T_DEC: []
T_HA: []
T_EQUI: []
AIRMASS: []
WCSAXES: []
CRVAL1: []
CRVAL2: []
CRPIX1: []
CRPIX2: []
CTYPE1: []
CTYPE2: []
CUNIT1: []
CUNIT2: []
CRTYPE1: []
CRTYPE2: []
CD1_1: []
CD1_2: []
CD2_1: []
CD2_2: []
EQUNOX: []
LONPOLE: []
LATPOLE: []
ASTRMS: []
SEEING: []
LIMMAG: []
ZP: []
DOMESTAT: []
M_STAT: []
TEMP_TEL: []
TEMP_IN: []
TEMP_OUT: []
TEMP_CAM: []
HUM_IN: []
HUM_OUT: []
PRESSURE: []
WINDSP: []
WINDDIR: []